name: MacOS

on:
  [push, pull_request]

jobs:
  macos_build:
    name: Build MeshLab (MacOS)
    runs-on: macos-latest
    strategy:
      matrix:
        precision: [single_precision, double_precision]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install dependencies
      run: |
        brew install libomp
        npm install -g appdmg
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Setup env variables
      id: envs
      shell: bash
      run: |
        if [ "${{matrix.precision}}" == "double_precision" ]; then
          echo  ::set-output name=artifact_suffix::"_double"
        else
          echo  ::set-output name=artifact_suffix::""
        fi
    - name: Configure and Build
      shell: bash
      run: |
        bash scripts/${{ runner.os }}/1_build.sh --${{ matrix.precision }} --nightly
    - name: Deploy
      shell: bash
      run: |
        bash scripts/${{ runner.os }}/2_deploy.sh
    - name: Import Cert and Key
      uses: apple-actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
        p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
    - name: Sign
      run: |
        codesign --options "runtime" --timestamp --force --deep --sign ${{ secrets.MACOS_CERT_ID }} src/install/meshlab.app
    - name: Notarize Release
      uses: devbotsxyz/xcode-notarize@v1
      with:
        product-path: "src/install/meshlab.app"
        appstore-connect-username: ${{ secrets.MACOS_NOTARIZATION_USER }}
        appstore-connect-password: ${{ secrets.MACOS_NOTARIZATION_PSSW }}
    - name: Create DMG
      shell: bash
      run: |
        bash scripts/${{ runner.os }}/3_dmg.sh
    - name: Upload MeshLab Portable
      uses: actions/upload-artifact@v2
      with:
        name: meshlab_macos_portable${{steps.envs.outputs.artifact_suffix}}
        path: src/install/MeshLab*.app
    - name: Upload DMG
      uses: actions/upload-artifact@v2
      with:
        name: meshlab_macos_dmg${{steps.envs.outputs.artifact_suffix}}
        path: src/install/MeshLab*.dmg
